services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081

  runner:
    image: ubuntu:latest
    container_name: runner

volumes:
  nexus-data:
