name: Release
description: Releases a new version of design system
inputs:
  token:
    description: Github token
    required: true
  mode:
    description: Release mode (major | minor | patch)
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Config git globals
      shell: bash
      run: |
        git config --global user.name "$(git log -n 1 --pretty=format:%an)"
        git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

    - name: Get Tag
      id: get-tag
      env:
        mode: ${{ inputs.mode }}
      shell: bash
      run: |
        current_version="$(git fetch --all --tags && git tag --list --sort=-creatordate | head -n 1)"
        echo "::debug::Current version is: $current_version"
        echo "current_version=${current_version}" >> $GITHUB_OUTPUT
        echo "new_version=1.0.6" >> $GITHUB_OUTPUT

    - name: Create Tag
      id: create-tag
      if: success() && steps.get-tag.outputs.new_version != ''
      env:
        tag: ${{ steps.get-tag.outputs.new_version }}
      shell: bash
      run: |
        git tag -a $tag -m "Tag $tag for design system"
        git push origin $tag

    - name: Build Changelog
      id: changelog
      if: success() && steps.get-tag.outputs.new_version != ''
      env:
        workspace: ${{ github.workspace }}
        old_tag: ${{ steps.get-tag.outputs.current_version }}
        new_tag: ${{ steps.get-tag.outputs.new_version }}
      shell: bash
      run: |
        cgl_content="$($workspace/build/release-docs.sh $old_tag $new_tag)"
        echo "content<<EOF"$'\n'"$cgl_content"$'\n'EOF >> "$GITHUB_OUTPUT"

    - name: Create Github Release
      if: success() && steps.get-tag.outputs.new_version != ''
      env:
        changelog: ${{ steps.changelog.outputs.content }}
        tag: ${{ steps.get-tag.outputs.new_version }}
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [! -z "$changelog" ]
        then
          gh release create "$tag" \
          --repo "$GITHUB_REPOSITORY" \
          --title "${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --notes $changelog \
          --verify-tag
        else
          gh release create "$tag" \
          --repo "$GITHUB_REPOSITORY" \
          --title "${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes \
          --verify-tag
        fi
