name: Release
description: Releases a new version of design system
inputs:
  token:
    description: Github token
    required: true
  mode:
    description: Release mode (major | minor | patch)
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout current branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}

    - name: Create tag and changelog
      id: tag-changelog
      shell: bash
      working-directory: ${{ github.workspace }}/build
      env:
        mode: ${{ inputs.mode }}
      run: ./release.sh

    - name: Create Github Release
      if: success() && steps.tag-changelog.outputs.new_version != ''
      env:
        changelog: ${{ steps.tag-changelog.outputs.content }}
        tag: ${{ steps.tag-changelog.outputs.new_version }}
        GH_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        if [ ! -z "$changelog" ]
        then
          echo "::debug::changelog available"
        else
          echo "::debug::changelog is NOT available"
        fi
