name: CI

on:
  push:

  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: "Release mode"
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Github release
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Invoke github release
        id: github-release
        uses: ./.github/workflows/actions/release
        with:
          token: ${{ github.token }}
          mode: ${{ inputs.mode }}
