name: CI

on:
  push:

  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: "Release mode"
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  build:
    name: Build and Test
    if: github.event_name == 'push'
    runs-on:
      group: Personalisation
      labels: [self-hosted, linux, x64]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Build docs
        run: npm run build:docs

      - name: Build system
        run: npm run build:system

      - name: Run tests
        run: npm run test

  publish-release:
    name: Create Release
    needs: [build]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on:
      group: Personalisation
      labels: [self-hosted, linux, x64]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        run: npm ci

      - name: Build system
        run: npm run build:system

      - name: Publish to NPM
        run: npm publish --registry https://npm.nos.to/ || true

  publish-docs:
    name: Publish Docs
    needs: [build]
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on:
      group: Personalisation
      labels: [self-hosted, linux, x64]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run build:docs

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync to S3
        run: cd dist/docs && aws s3 sync . s3://nosto-design-system/

  release:
    name: Github release
    if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - name: Create github release
        id: github-release
        uses: ./.github/workflows/actions/release
        with:
          token: ${{ github.token }}
          mode: ${{ inputs.mode }}
