name: CI & Release

on:
  push:

  workflow_dispatch:
    inputs:
      mode:
        type: choice
        description: "Release mode"
        required: true
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  ci:
    name: Build, Test and Documentation
    if: github.event_name == 'push'
    uses: "./.github/workflows/build.yml"

  release:
    name: Github Release & Publish to NPM
    if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
    uses: "./.github/workflows/release.yml"
    secrets:
      token: ${{ github.token }}
    with:
      mode: ${{ inputs.mode }}
