name: CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        #run: npm ci
        run: npm install

      - name: Run build
        run: npm run build

      #- name: Build docs
      #  run: npm run build:docs

      #- name: Build system
      #  run: npm run build:system

      #- name: Run tests
      #  run: npm run test

  publish-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        run: npm install

      #- name: Build docs
      #  run: npm run build:docs

      #- name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-region: us-east-1

      #- name: Sync to S3
      #  run: cd dist/docs && aws s3 sync . s3://nosto-design-system/
