name: Release

on:
  workflow_call:
    inputs:
      mode:
        type: string
        description: Release mode (major | minor | patch)
        required: true

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: ./
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0
        with:
          gh-cli-version: 2.48.0

      - name: Generate tag and changelog
        id: tag-changelog
        shell: bash
        working-directory: ${{ github.workspace }}/.github/workflows
        env:
          mode: ${{ inputs.mode }}
        run: ./scripts/release.sh

      - name: Create Github tag
        id: tag-create
        shell: bash
        env:
          new-version: ${{ steps.tag-changelog.outputs.new_version }}
        run: |
          git tag -a $new-version -m "Tag $new-version for design system"
          git push origin --porcelain $new-version

      - name: Create Github Release
        if: success() && steps.tag-changelog.outputs.new_version != ''
        env:
          changelog: ${{ steps.tag-changelog.outputs.content }}
          tag: ${{ steps.tag-changelog.outputs.new_version }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          if [ ! -z "$changelog" ]
          then
            echo "::debug::changelog available"
            gh release create "$tag" \
            --repo "$GITHUB_REPOSITORY" \
            --title "${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --notes "$changelog" \
            --verify-tag
          else
            echo "::debug::changelog is NOT available"
            gh release create "$tag" \
            --repo "$GITHUB_REPOSITORY" \
            --title "${GITHUB_REPOSITORY#*/} ${tag#v}" \
            --generate-notes \
            --verify-tag
          fi

  npm-publish:
    runs-on: ubuntu-latest
    needs: github-release
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set registry
        run: npm set registry https://npm.nos.to

      - name: Install dependencies
        run: npm install

      #- name: Build system
      # run: npm run build:system

      #- name: Publish to NPM
      #  run: npm publish --registry https://npm.nos.to/ || true
